name: flutter_auth
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_svg: ^1.1.0
  curved_navigation_bar: ^1.0.3
  smooth_page_indicator: ^1.0.0+2
  line_awesome_flutter: ^2.0.0
  flutter_screenutil: ^5.6.0
  animated_theme_switcher: ^2.0.7
  carousel_slider: ^4.2.0
  flutter_progress_hud: ^2.0.2
  dio: ^4.0.6
  convert: ^3.1.1
  universal_platform: ^1.0.0+1
  bottom_bar_page_transition: ^2.0.0

  url_launcher: ^6.1.7
  flutter_share: ^2.0.0
  share_plus: ^6.3.0

  percent_indicator: ^4.2.2
  lottie: ^2.1.0
  provider: ^6.0.4

  http: ^0.13.5
  api_cache_manager: ^1.0.2
  snippet_coder_utils: ^1.0.12
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/images/logo.png"
  image_path_android: "assets/images/logo.png"
  adaptive_icon_background: "assets/images/logoback.png"
  adaptive_icon_foreground: "assets/images/logoback.png"


  flutter_lints: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    # - loading.json
    #  - images/a_dot_ham.jpeg
    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/assets-and-images/#resolution-aware.
    # For details regarding adding assets from package dependencies, see
    # https://flutter.dev/assets-and-images/#from-packages
    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    #fonts:
      #- family: SFPro
      #fonts:
      #  - asset: fonts/SFProText-Light.ttf
      #  - asset: fonts/SFProText-Medium.ttf
      #  - asset: fonts/SFProText-Regular.ttf
      #  - asset: fonts/SFProText-Semibold.ttf
      #  - asset: fonts/FProText-Bold.ttf
    #    weight: 700

  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
